version: 1.2
workflows:
- name: StatisticalPhasingPhase2
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_phase2.wdl
- name: VcfdistAndSwitchEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phasing/VcfdistAndSwitchEvaluation.wdl
