version: 1.2
workflows:
- name: HierarchicallyMergeVcfs
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/HierarchicallyMergeVcfs.wdl
- name: PhysicalPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/PhysicalPhasing.wdl
- name: ChromosomePhasedPanelCreationFromHiPhase
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/ChromosomePhasedPanelCreationFromHiPhase.wdl
- name: FixVariantCollisions
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/FixVariantCollisions.wdl
- name: KAGEPanelWithPreprocessing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/KAGEPanelWithPreprocessing.wdl
- name: KAGECasePerChromosomeFlexscattered
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/KAGECasePerChromosomeFlexscattered.wdl
- name: GatherKAGECases
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/GatherKAGECases.wdl
- name: GLIMPSEBatchedCasePerChromosome
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/GLIMPSEBatchedCasePerChromosome.wdl
- name: GLIMPSEBatchedCasePerChromosomeNoTranspose
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/GLIMPSEBatchedCasePerChromosomeNoTranspose.wdl
- name: GLIMPSEBatchedCasePerChromosomeSingleBatch
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/GLIMPSEBatchedCasePerChromosomeSingleBatch.wdl
- name: AnnotateAndPop
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/kage/AnnotateAndPop.wdl
- name: PanGenieIndex
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/pangenie/PanGenieIndex.wdl
- name: PanGenieGenotype
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/pangenie/PanGenieGenotype.wdl
- name: PanGeniePanelCreation
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/pangenie/PanGeniePanelCreation.wdl
- name: VcfdistAndOverlapMetricsEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phased-panel/VcfdistAndOverlapMetricsEvaluation.wdl
- name: ConcatAndEvaluateReduced
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phased-panel/ConcatAndEvaluateReduced.wdl
- name: LeaveOutEvaluationReduced
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/kage/LeaveOutEvaluationReduced.wdl
