version: 1.2
workflows:
- name: PhysicalAndStatisticalPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/PhysicalAndStatisticalPhasing.wdl
- name: PanGenieCase
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/pangenie/PanGenieCase.wdl
- name: PanGeniePanelCreation
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/pangenie/PanGeniePanelCreation.wdl
- name: VcfdistEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/vcfdist/VcfdistEvaluation.wdl
- name: PhasedPanelEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phased-panel/PhasedPanelEvaluation.wdl
- name: LeaveOutEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/kage/LeaveOutEvaluation.wdl
- name: LeaveOneOutEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/kage/LeaveOneOutEvaluation.wdl
